services:
  flask:
    image: flask-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nginx
    healthcheck:
      test: curl --fail http://127.0.0.1:5000/health || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    healthcheck:
      test: curl --fail http://127.0.0.1:80/health || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s