name: Deploy Docker Compose on EC2
on:
  push:
    tags:
      - '*'

#env:
#  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  TERRAFORM_CLOUD_TOKENS: terraform.example.com=${{ secrets.TF_REGISTRY_TOKEN }}
#  TERRAFORM_SSH_KEY: ${{ secrets.TERRAFORM_SSH_KEY }}

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create Terraform Plan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      - name: get caller identity 1
        run: |
          aws sts get-caller-identity
      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform
