name: Deploy Docker Compose on EC2
on:
  push:
    tags:
      - '*'
env:
 TF_LOG: INFO
 AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 TF_VAR_aws_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
 TF_VAR_aws_secret: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create Terraform Plan
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
     - name: Checkout the repository to the runner
       uses: actions/checkout@v2

     - name: Set up SSH
       run: |
         mkdir -p ~/.ssh/aws
         echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/aws/aws_key.pub

     - name: Setup Terraform with specified version on the runner
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.5.7

     - name: Terraform init
       id: init
       run: terraform init

     - name: Terraform format
       id: fmt
       run: terraform fmt -check

     - name: Terraform validate
       id: validate
       run: terraform validate

     - name: Terraform plan
       id: plan
       run: terraform plan -no-color -input=false
       continue-on-error: true

     - name: Terraform Plan Status
       if: steps.plan.outcome == 'failure'
       run: exit 1

     - name: Approve Plan (Manual)
       uses: trstringer/manual-approval@v1
       timeout-minutes: 10

     - name: Terraform Apply
       run: terraform apply -auto-approve -input=false