name: Deploy Docker Compose on EC2
on:
  push:
    tags:
      - '*'

#env:
#  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#  TERRAFORM_CLOUD_TOKENS: terraform.example.com=${{ secrets.TF_REGISTRY_TOKEN }}
#  TERRAFORM_SSH_KEY: ${{ secrets.TERRAFORM_SSH_KEY }}

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Create Terraform Plan
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_VAR_AWS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_VAR_AWS_SECRET }}
      AWS_DEFAULT_REGION: us-east-2
      AWS_DEFAULT_OUTPUT: json
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: terraform
